"""Snapshot the reviewed queue as an immutable mapping artifact.

The review queue is regenerated by build_ingred_review.py and its human
columns survive only by norm_key lookup. This file is the durable record:
one row per reviewed ingredient key, committed to the repo, cited in the
paper, and the sole input to build_ingredients.py.

n_lines is carried so the artifact can reproduce its own line-weighted
coverage without recipe_keys.csv, which is regenerable.

fallback_* is merged in from final/fallback_map.csv, a hand-maintained file
for foods no IFCT row covers. It is kept separate from chosen_ifct_code so
"IFCT coverage" and "total coverage" stay separately reportable, and so
adding a USDA tier later is a new file row rather than a schema change.
"""
import csv
from malabardb import paths

# added fallback_code and fallback_source
FIELDS = ["norm_key", "generic_name", "n_lines", "chosen_ifct_code",
          "hierarchical", "rank_found", "fallback_code", "fallback_source",
          "reviewer_notes"]

rows = [r for r in csv.DictReader(paths.REVIEW_QUEUE_INGREDIENTS.open(encoding="utf-8"))
        if int(r["n_lines"]) > 0]

unreviewed = [r["norm_key"] for r in rows
              if not r["chosen_ifct_code"].strip() and not r["rank_found"].strip()]
if unreviewed:
    raise SystemExit(f"{len(unreviewed)} keys not reviewed: {unreviewed[:10]}")

# hierarchical describes a match; an absent key has no match to describe.
stray = [r["norm_key"] for r in rows
         if not r["chosen_ifct_code"].strip() and r["hierarchical"].strip()]
if stray:
    raise SystemExit(f"hierarchical set on absent keys: {stray}")

# merge the fallback tier 
fallback = {}
if paths.FALLBACK_MAP.exists():
    fallback = {r["norm_key"]: r
                for r in csv.DictReader(paths.FALLBACK_MAP.open(encoding="utf-8"))}
    ghosts = sorted(set(fallback) - {r["norm_key"] for r in rows})
    if ghosts:
        raise SystemExit(f"fallback_map names keys not in the corpus: {ghosts}")

for r in rows:
    fb = fallback.get(r["norm_key"], {})
    r["fallback_code"] = fb.get("fallback_code", "").strip()
    r["fallback_source"] = fb.get("fallback_source", "").strip()
    if r["chosen_ifct_code"].strip() and r["fallback_code"]:
        raise SystemExit(f"{r['norm_key']}: has both an IFCT code and a fallback")

with paths.INGREDIENT_IFCT_MAP.open("w", newline="", encoding="utf-8") as fh:
    w = csv.DictWriter(fh, fieldnames=FIELDS)
    w.writeheader()
    w.writerows({k: r[k] for k in FIELDS} for r in rows)

total = sum(int(r["n_lines"]) for r in rows)
linked = sum(int(r["n_lines"]) for r in rows if r["chosen_ifct_code"].strip())
fb_lines = sum(int(r["n_lines"]) for r in rows if r["fallback_code"])   # NEW

print(f"froze {len(rows)} keys / {total} lines -> {paths.INGREDIENT_IFCT_MAP}")
print(f"  IFCT     {linked} lines ({linked/total*100:.1f}%)")
print(f"  fallback {fb_lines} lines ({fb_lines/total*100:.1f}%)")
print(f"  total    {linked+fb_lines} lines ({(linked+fb_lines)/total*100:.1f}%)")